#! /bin/sh
# /etc/init.d/noip

### BEGIN INIT INFO
# Provides:          noip
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting modem"
    # run application you want to start
    /usr/sbin/usb_modeswitch -c /etc/usb_modeswitch.d/12d1\:1446
    nohup wvdial bsnl &
    ;;
  stop)
    echo "Stopping modem"
    # kill application you want to stop
    killall wvdial
    ;;
  *)
    echo "Usage: /etc/init.d/start_modem {start|stop}"
    exit 1
    ;;
esac

exit 0 
